### ISSUE TITLE
Can I use multi iavl trees with one db?

### ISSUE THREAD

**Issue by anarcher** [tendermint/iavl#103]
Like using MPT for ethereum storage tries, can I make multiple iavl trees for each account storages?
Iavl tree looks great to world state,but I am not sure how to make multiple iavl trees with one db. 
If nodedb can handle such as like namespace (prefix) per trees, It can work.. IMHO. Is it right?

**Comment by silasdavis** [comment]
This is something I would also like to implement this for: https://github.com/hyperledger/burrow. For various start buckets it would be useful to have a forest of state roots (like per account). It ought to be possible to a hybrid prefix tree (for namespaces for example) with some subroot being the root of an IAVL tree.

You can take a look at: https://github.com/tendermint/tendermint/blob/master/libs/db/prefix_db.go which ought to get you much of the way there:

```go
tree1 := iavl.NewMutableTree(dbm.NewPrefixDB(db, []byte("prefix1"), cacheCapacity)
tree2 := iavl.NewMutableTree(dbm.NewPrefixDB(db, []byte("prefix2"), cacheCapacity)
```

**Comment by anarcher** [comment]
@silasdavis Thanks very much!  I like this approach for handling multiple trees.  I will close this issue. :-)
