### ISSUE TITLE
add information about which hashing algorithm is used

### ISSUE THREAD

**Issue by zramsay** [tendermint/iavl#11]
@simonvadee commented on [Mon Sep 25 2017](https://github.com/tendermint/merkleeyes/issues/57)

I have an ABCI application storing IAVLProofs and one has to be able to validate these proofs outside of the application's context (and independently from the merkleeyes module). The application also store different kinds of merkle trees (using some other hashing algorithm), but all of them implementing the IAVL format to store merkle proofs :
```
type IAVLProof struct {
	LeafHash   []byte
	InnerNodes []IAVLProofInnerNode
	RootHash   []byte
}

type IAVLProofInnerNode struct {
	Height int8
	Size   int
	Left   []byte
	Right  []byte
}
```
The only information missing to independently validate a proof is the hsh function used to build the IAVL tree (`ripemd160` in tendermint's case). My suggestion is to add a field `hashFunction`, either in `IAVLProofInnerNode` or directly in `IAVLProof` to make it possible for merkle proof validation systems to work with several kinds of merkle trees, including your IAVL+ implementation.

**Comment by silasdavis** [comment]
https://github.com/multiformats/multihash may be worth considering it as a possibly portable hash-with-metadata format. Rather similar to amino encoding, but the type bytes are standardised.

**Comment by ValarDragon** [comment]
I'm opposed to multihashes. I don't like their design decision of making hashes all include the length. Plus increasing the tree size seems like a bad idea imo. I'd rather use full sha2 then use multihashes. I don't see why enforcing that a tree only have one hash type is limiting, and then convey that hash type once in the initial IBC connection, don't slow down every subsequent thing ever.

**Comment by silasdavis** [comment]
I don't disagree. Let's close this issue then :)
