### ISSUE TITLE
Bump Tendermint version to v0.26.0?

### ISSUE THREAD

**Issue by nnkken** [tendermint/iavl#117]
I see that the `develop` branch is already on `version = "=v0.26.0-rc0"`.

As v0.26.0 is quite a large release, and it also moves from 20 bytes to 32 bytes hashes, would you consider bumping the Tendermint version in `Gopkg.toml` of the master branch to v0.26.0?

**Comment by Liamsi** [comment]
Thanks for the nudge @nnkken. Updated in https://github.com/tendermint/iavl/pull/118 (review pending).
