### ISSUE TITLE
Evaluate feasibility of deterministic indexical chunk mapping for state sync

### ISSUE THREAD

**Issue by cwgoes** [tendermint/iavl#135]
Is there an efficient way we can map from integer indices to sub-key-spaces of a particular tree version, such that chunks would be approximately the same size or at least size-bounded, and individually provable (some metadata about top-level tree-structure can be transmitted up front)?

ref https://github.com/tendermint/tendermint/issues/828

cc @Liamsi @ebuchman

**Comment by ackratos** [comment]
would you like see a new proposal here: https://github.com/tendermint/tendermint/issues/828#issuecomment-479859591

**Comment by cwgoes** [comment]
https://github.com/tendermint/tendermint/pull/3799#discussion_r303619323

**Comment by cwgoes** [comment]
Closing in favour of more up-to-date discussions.
