### ISSUE TITLE
Inspect cosmos-sdk db?

### ISSUE THREAD

**Issue by cbarraford** [tendermint/iavl#182]
I have a basic question. Im building a cosmos-sdk app and running into a problem joining two nodes. I get an error that looks like the following despite both nodes using the same genesis file.

```
E[2019-10-31|06:04:59.442] enterPrevote: ProposalBlock is invalid       module=consensus height=2 round=0 err="Wrong Block.Header.AppHash.  Expected 0800C9102DB9D3D0E288E8D4FA08DF74399498A855D25CF1EAFE2E8F5C630FF3, got 137CB732C9449914B4F97126309AAFCB2B3A2DD231CED3D48460F13C2DCE7D7B"
```

I'd like to inspect the database of cosmos and I thought this was the tool for that, but I can't seem to figure out how to use it properly and I can't find any example or docs on how to use it with cosmos. Maybe im barking up the wrong tree.

I start my chain, add a few records into the kvstore, and my db is empty somehow.
```
iaviewer data ~/.ssd/data/application.db                                                                                             ✓  08:03:53
Got version: 0
Printing all keys with hashed values (to detect diff)
Hash:
Size: 0
```

Any insights? thanks in advance.

**Comment by arnabmitra** [comment]
same? any insight?

**Comment by cbarraford** [comment]
For me, one of the devs put a timestamp into the chain (which isn't a good idea). That was the root cause in our case

**Comment by erikgrinaker** [comment]
Sorry for the late reply here! The Cosmos SDK may not be persisting data to disk, which is why you're seeing an empty database. I believe the default setting only persists every 100,000 heights, so during development you may want to change the pruning settings to persist every block to disk (`--pruning nothing` or something similar).

> For me, one of the devs put a timestamp into the chain

That'll do it - glad to hear you found the problem!

Let us know if changing the pruning settings don't help.

**Comment by cbarraford** [comment]
good tip on the pruning. Also, worth noting that setting pruning on cosmos v0.37 is broken! (works in v0.38 though). So you can't have a pruning setting other than default on that version.

**Comment by alexanderbez** [comment]
@cbarraford, 0.37 is marked as broken in the release. See the release notes. It's recommended to use 0.38.x
