### ISSUE TITLE
Proof Spec

### ISSUE THREAD

**Issue by AdityaSripal** [tendermint/iavl#185]
The current spec has no documentation on how proofs are constructed and verified. Continuation of work specified in #56 

Need writeup on:

- [ ] RangeProof
- [ ] Components of Proofs (e.g. ProofInnerNode, PathToLeaf)
- [ ] Proof of Value
- [ ] Proof of Abscence
- [ ] Proof Operator abstraction

**Comment by marbar3778** [comment]
closing this in favor of #204
