### ISSUE TITLE
SaveVersion won't save an empty tree

### ISSUE THREAD

**Issue by kentquirk** [tendermint/iavl#36]
This is admittedly an edge case, but SaveVersion returns error on attempting to save an empty tree. 

The following code panics:

```go
package main

import (
	"github.com/tendermint/iavl"
	"github.com/tendermint/tmlibs/db"
)

func main() {
	// create a new database
	db := db.NewDB("bug", db.GoLevelDBBackendStr, "")
	state := iavl.NewVersionedTree(500, db)
	height := state.LatestVersion() + 1

	_, err := state.SaveVersion(height)
	if err != nil {
		panic(err)
	}
}
```

This also happens if you remove the last key and attempt to save (which is how we detected it).

There's not a good workaround. Testing the returned error for equality to `iavl.ErrNilRoot` doesn't help, because if you are attempting to preserve history but remove all keys, that last key removal was not saved.

A workaround I don't particularly like is to store a single "impossible" key in the tree at creation so that it's basically impossible to remove the last key.

If you would please give some guidance on how you think this should be handled, I will try to create a PR that fixes it.

**Comment by erikgrinaker** [comment]
That has since been fixed, works for me in the latest release.
