### ISSUE TITLE
VersionedTree.LatestVersion() no longer exists in v0.6.1

### ISSUE THREAD

**Issue by coriolinus** [tendermint/iavl#43]
How do we get the latest version now? The [docs](https://godoc.org/github.com/tendermint/iavl) still use that function as an example, but the example is the only place in that file where the string `LatestVersion` exists.

**Comment by coriolinus** [comment]
It's returned as the second return value from `SaveVersion` now, apparently.

This is a breaking change which wasn't listed in the changelog.

**Comment by ebuchman** [comment]
Thanks for pointing this out, and sorry for the inconvenience. Unfortunately this repo was in a bit of a weird state for sometime and the changelog was not being continuously updated, so we may have missed some items when we finally cut the release. We will do a much better job of communicating changes moving forward.

You can get the latest version with `LoadVersion(0)` as per https://github.com/tendermint/iavl/blob/master/versioned_tree.go#L79

We will update the docs and the changelog.

**Comment by coriolinus** [comment]
The problem isn't in loading the tree state; `Load()` handles that. The issue is that there is currently no way to get the tree's current height except from the second parameter returned by `SaveVersion()`. 

Strictly speaking, this isn't a problem for this library; we could manually persist the tree's height. However, if this is to be used as the backing store for an ABCI application, we need to get that height for the InfoQuery connection. The height is stored as part of the tree's structure, but without the `LatestVersion()` function, there is no longer any way to get it.

It would be very nice to have either an additional return value from `Load()` to return the current height, or the `LatestVersion()` function back.

**Comment by silasdavis** [comment]
Agreed, we'd do well to have this back in.

**Comment by ebuchman** [comment]
Merged, sorry for the delay!

**Comment by coriolinus** [comment]
No problem, thanks for merging!
