### ISSUE TITLE
Clarify tree.Hash / Skipped test TestProof

### ISSUE THREAD

**Issue by Liamsi** [tendermint/iavl#50]
Find out why [`TestProof`](https://github.com/tendermint/iavl/blob/fd37a0fa3a7454423233bc3d5ea828f38e0af787/basic_test.go#L389-L390) fails (tree root never seems to match here). 
It's not clear why this is a race-condition. Either 1) fix test, 2) clarify why it is skipped, or 3) remove test (only if the test does not make sense).

https://github.com/tendermint/iavl/blob/35f66e53d9b01e83b30de68b931f54b2477a94c9/basic_test.go#L392-L422

**Comment by Liamsi** [comment]
This is what I think the problem is:

While `tree.Iterate` is called with `tree.Hash()` as the root hash, `tree.Hash()` is called on the latest versioned tree (the persisted tree, see [here](https://github.com/tendermint/iavl/blob/fd37a0fa3a7454423233bc3d5ea828f38e0af787/versioned_tree.go#L51-L53)). tree.Iterate() on the other side operates on the whole tree (incl. the non-persisted / orphaned nodes); see [here](https://github.com/tendermint/iavl/blob/fd37a0fa3a7454423233bc3d5ea828f38e0af787/tree.go#L210)

**Comment by Liamsi** [comment]
After discussing with @jlandrews, will open a PR with the above changes which will fix the test.

**Comment by marbar3778** [comment]
resolved in #92
