### ISSUE TITLE
Remove dependency on go-wire

### ISSUE THREAD

**Issue by Liamsi** [tendermint/iavl#51]
iavl uses/vendors go-wire (which depends on ripemd160)
Make it either indpendendent from go-wire / amino, or update to amino.

Remove ripemd dependency from gilde file(s).

**Comment by zmanian** [comment]
We need to make some decision here.

We clearly need to remove the go-wire dependency.

Based on how wire is invoked right now, it is only used to encode fixed length structures.

If we switch to amino, compatible implementations will need to have some awareness of amino. To me this looks like the `typ3` table and `varint` encoding maybe but not the`disfix` identifier.

Are we comfortable requiring this?

One use case for compatible implementations will implementing IBC in lotion and in our partners stacks.

**Comment by zmanian** [comment]
I think this is semi relevant to 
https://github.com/cosmos/cosmos-sdk/pull/454/files

**Comment by Liamsi** [comment]
Thanks for your input @zmanian. There is a related PR #53. I'm not sure yet if I found a bug [here](https://github.com/tendermint/iavl/pull/53#issuecomment-386603451) or if the way iavl uses amino needs to be updated.

**Comment by ebuchman** [comment]
Looks like IAVL never actually encodes a struct, so I dont think it needs to know the typ3 table - it only calls `EncodeIntXxx` and  `EncodeByteSlice`, which AFAIK are just purely proto3 encodings of ints and byte slices. 

That sounds pretty ideal for this.

**Comment by zmanian** [comment]
`EncodeIntXxx` is just big endian fixed size int encoding

`EncodeByteSlice` is varint LEB128 encoded length prefixed bytes

**Comment by ebuchman** [comment]
Int32 and Int64 are the fixed-size big-endian, but Int8 is apparently encoded as a Varint ...

In any case, there's nothing amino specific about these, right ?

**Comment by zmanian** [comment]
Yeah 8 and 18 are varints

**Comment by zmanian** [comment]
Yeah these aren't amino things. But LEB128 varints and bigendian fixed with ints are specifications the protobufs and amino incorporate

**Comment by Liamsi** [comment]
Closing this. The go-wire (golang package) dependency was removed with #53. I'll update the documentation to clarify encoding specific things. 

linking to #56
