### ISSUE TITLE
Write Spec

### ISSUE THREAD

**Issue by ebuchman** [tendermint/iavl#56]
We need a clear specification of how this works, most importantly how data is serialized and hashes are computed.

A secondary concern is how it's cached and persisted on disk.

**Comment by Liamsi** [comment]
Cool, I'll work on this. Might be a good way to fully familiarize myself with the implementation. I might have some questions though.

**Comment by Liamsi** [comment]
From the last libs call: @jaekwon suggested that this is a post-launch requirement.  @jlandrews started a document a while ago. We will update it when #92 is merged but finalize it later.

**Comment by marbar3778** [comment]
@AdityaSripal can we close this because of https://github.com/tendermint/iavl/pull/167 or do you still have things you would like to accomplish?

**Comment by AdityaSripal** [comment]
Yes, we can close this and I'll writeup a more specific issue for writing up proof spec
