### ISSUE TITLE
Proposal: export `proofLeafNode`

### ISSUE THREAD

**Issue by Liamsi** [tendermint/iavl#73]
Currently, `proofLeafNode` is not exported. While it is good practice to export only what is really neccessary (and hide fields and functionality that are not essential for the API), I think this type should be public/exported: If someone is about to write a verifier in another language, he needs to know enough details what a `RangeProof` consists of (and `proofLeafNode` is part of that):
https://github.com/tendermint/iavl/blob/f2c70966873724a199ea37d0cbfc8b50baa0f7bf/proof_range.go#L12-L21

Exporting the type would also create a proper godoc item. Similarly, `proofInnerNode` (as  `PathToLeaf` is just a type alias to `[]proofInnerNode`).

cc @jlandrews @jaekwon

**Comment by tessr** [comment]
I am in favor of this, I think. I just found myself wishing these fields were exported while trying to write a toy program--not sure if that's actually representative of what people want to do with this package, though.

**Comment by erikgrinaker** [comment]
Yeah, I’d say it’s generally bad form to expose private types as publicly accessible values - i.e. `Leaves []proofLeafNode` elements are publicly accessible, but of a private type.

**Comment by tessr** [comment]
Another great point.
