### ISSUE TITLE
dep: Change the tendermint import

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/iavl#90]
Currently we're using an old tendermint version, and we use an equal sign. Because of this, we have to use an override for tendermint in the sdk's gopkg.toml. This makes it hard to import the sdk, and use any type from tendermint. This is because overrides _do not_ apply transitively with dep. Only overrides in the top directory you're calling `dep ensure` from get applied. Therefore in your downstream application you have to add an override import yourself, which is confusing,

We should change the tendermint import to be `^v0.22.0`, or `^v0.22.4`. (In the SDK its just getting replaced with `v0.22.4` anyway) This would alleviate issues in the future as well.

**Comment by Liamsi** [comment]
I think, I agree with @silasdavis here: We should duplicate the few methods we use from tendermint instead of updating the dependency. See also: https://github.com/tendermint/iavl/issues/46#issuecomment-406555769

**Comment by ValarDragon** [comment]
That sounds more optimal to me. However, I'm not sure what the ETA on that is. The fix I'm proposing is a very quick fix.

**Comment by Liamsi** [comment]
resolved by https://github.com/tendermint/iavl/pull/91
